version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-west-2:277339514346:task-definition/fercos-ecs-teste:1"
        LoadBalancerInfo:
          ContainerName: "ecs-fercos-container"
          ContainerPort: 80
